In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [56]:
data =iris.data

In [63]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [68]:
df.values

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [98]:
data = iris.data

In [100]:
data_list = data.tolist()#df1 = data.stack().to_frame().T

In [90]:
records=[]
for i in range(0,150):
    for j in range(0,4):
        print iris.data

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [101]:
from apyori import apriori
rules = apriori(data_list, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2)

In [102]:
results=list(rules)

In [103]:
results

[RelationRecord(items=frozenset([1.1, 0.1]), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset([1.1]), items_add=frozenset([0.1]), confidence=0.25, lift=6.25)]),
 RelationRecord(items=frozenset([1.5, 0.1]), support=0.02666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset([0.1]), items_add=frozenset([1.5]), confidence=0.6666666666666667, lift=3.8461538461538463)]),
 RelationRecord(items=frozenset([3.1, 0.1]), support=0.02, ordered_statistics=[OrderedStatistic(items_base=frozenset([0.1]), items_add=frozenset([3.1]), confidence=0.5, lift=6.25), OrderedStatistic(items_base=frozenset([3.1]), items_add=frozenset([0.1]), confidence=0.25, lift=6.25)]),
 RelationRecord(items=frozenset([4.1, 0.1]), support=0.006666666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset([4.1]), items_add=frozenset([0.1]), confidence=0.25, lift=6.25)]),
 RelationRecord(items=frozenset([4.3, 0.1]), support=0.006666666666666667, ordered_stat

In [135]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

data_list_sets = iris.data.applymap(encode_units)

AttributeError: 'numpy.ndarray' object has no attribute 'applymap'

In [120]:
#dataset = [[1, 3, 4], [2, 3, 5], [1, 2, 3, 5], [2, 5]]

In [121]:
def createC1(dataSet):
    C1 = []
    for transaction in dataSet:
        for item in transaction:
            if not [item] in C1:
                C1.append([item])
                
    C1.sort()
    return list(map(frozenset, C1))#use frozen set so we
                            #can use it as a key in a dict  

In [122]:
C1 = createC1(data_list)

In [123]:
C1

[frozenset({0.1}),
 frozenset({0.2}),
 frozenset({0.3}),
 frozenset({0.4}),
 frozenset({0.5}),
 frozenset({0.6}),
 frozenset({1.0}),
 frozenset({1.1}),
 frozenset({1.2}),
 frozenset({1.3}),
 frozenset({1.4}),
 frozenset({1.5}),
 frozenset({1.6}),
 frozenset({1.7}),
 frozenset({1.8}),
 frozenset({1.9}),
 frozenset({2.0}),
 frozenset({2.1}),
 frozenset({2.2}),
 frozenset({2.3}),
 frozenset({2.4}),
 frozenset({2.5}),
 frozenset({2.6}),
 frozenset({2.7}),
 frozenset({2.8}),
 frozenset({2.9}),
 frozenset({3.0}),
 frozenset({3.1}),
 frozenset({3.2}),
 frozenset({3.3}),
 frozenset({3.4}),
 frozenset({3.5}),
 frozenset({3.6}),
 frozenset({3.7}),
 frozenset({3.8}),
 frozenset({3.9}),
 frozenset({4.0}),
 frozenset({4.1}),
 frozenset({4.2}),
 frozenset({4.3}),
 frozenset({4.4}),
 frozenset({4.5}),
 frozenset({4.6}),
 frozenset({4.7}),
 frozenset({4.8}),
 frozenset({4.9}),
 frozenset({5.0}),
 frozenset({5.1}),
 frozenset({5.2}),
 frozenset({5.3}),
 frozenset({5.4}),
 frozenset({5.5}),
 frozenset({

In [124]:
def scanD(D, Ck, minSupport):
    ssCnt = {}
    for tid in D:
        for can in Ck:
            if can.issubset(tid):
                if not can in ssCnt: ssCnt[can]=1
                else: ssCnt[can] += 1
    numItems = float(len(D))
    retList = []
    supportData = {}
    for key in ssCnt:
        support = ssCnt[key]/numItems
        if support >= minSupport:
            retList.insert(0,key)
        supportData[key] = support
    return retList, supportData

In [125]:
D = list(map(set,data_list))

In [126]:
D

[{0.2, 1.4, 3.5, 5.1},
 {0.2, 1.4, 3.0, 4.9},
 {0.2, 1.3, 3.2, 4.7},
 {0.2, 1.5, 3.1, 4.6},
 {0.2, 1.4, 3.6, 5.0},
 {0.4, 1.7, 3.9, 5.4},
 {0.3, 1.4, 3.4, 4.6},
 {0.2, 1.5, 3.4, 5.0},
 {0.2, 1.4, 2.9, 4.4},
 {0.1, 1.5, 3.1, 4.9},
 {0.2, 1.5, 3.7, 5.4},
 {0.2, 1.6, 3.4, 4.8},
 {0.1, 1.4, 3.0, 4.8},
 {0.1, 1.1, 3.0, 4.3},
 {0.2, 1.2, 4.0, 5.8},
 {0.4, 1.5, 4.4, 5.7},
 {0.4, 1.3, 3.9, 5.4},
 {0.3, 1.4, 3.5, 5.1},
 {0.3, 1.7, 3.8, 5.7},
 {0.3, 1.5, 3.8, 5.1},
 {0.2, 1.7, 3.4, 5.4},
 {0.4, 1.5, 3.7, 5.1},
 {0.2, 1.0, 3.6, 4.6},
 {0.5, 1.7, 3.3, 5.1},
 {0.2, 1.9, 3.4, 4.8},
 {0.2, 1.6, 3.0, 5.0},
 {0.4, 1.6, 3.4, 5.0},
 {0.2, 1.5, 3.5, 5.2},
 {0.2, 1.4, 3.4, 5.2},
 {0.2, 1.6, 3.2, 4.7},
 {0.2, 1.6, 3.1, 4.8},
 {0.4, 1.5, 3.4, 5.4},
 {0.1, 1.5, 4.1, 5.2},
 {0.2, 1.4, 4.2, 5.5},
 {0.1, 1.5, 3.1, 4.9},
 {0.2, 1.2, 3.2, 5.0},
 {0.2, 1.3, 3.5, 5.5},
 {0.1, 1.5, 3.1, 4.9},
 {0.2, 1.3, 3.0, 4.4},
 {0.2, 1.5, 3.4, 5.1},
 {0.3, 1.3, 3.5, 5.0},
 {0.3, 1.3, 2.3, 4.5},
 {0.2, 1.3, 3.2, 4.4},
 {0.6, 1.6,

In [127]:
L1,suppData = scanD(D,C1,0.5)

In [128]:
L1

[]

In [129]:
def aprioriGen(Lk, k): #creates Ck
    retList = []
    lenLk = len(Lk)
    for i in range(lenLk):
        for j in range(i+1, lenLk): 
            L1 = list(Lk[i])[:k-2]; L2 = list(Lk[j])[:k-2]
            L1.sort(); L2.sort()
            if L1==L2: #if first k-2 elements are equal
                retList.append(Lk[i] | Lk[j]) #set union
    return retList

In [130]:
def apriori(dataSet, minSupport = 0.5):
    C1 = createC1(dataSet)
    D = list(map(set, dataSet))
    L1, supportData = scanD(D, C1, minSupport)
    L = [L1]
    k = 2
    while (len(L[k-2]) > 0):
        Ck = aprioriGen(L[k-2], k)
        Lk, supK = scanD(D, Ck, minSupport)#scan DB to get Lk
        supportData.update(supK)
        L.append(Lk)
        k += 1
    return L, supportData

In [131]:
L,suppData = apriori(D)

In [132]:
L

[[]]