In [1]:
# import numpy
# create array x
import numpy as np
x = np.array([2,4,6])

In [2]:
# print the shape of x
np.shape(x)

(3,)

In [48]:
# create a two dimensional array
d_array = np.array([[10, 0, 0, 0],[0, 20, 0, 1]])
d_array


array([[10,  0,  0,  0],
       [ 0, 20,  0,  1]])

In [49]:
# print shape of 2d array
np.shape(d_array)


(2, 4)

In [52]:
# reshape the array to 4X2
new = np.reshape(d_array, (4,2))
new

array([[10,  0],
       [ 0,  0],
       [ 0, 20],
       [ 0,  1]])

In [53]:
np.shape(new)

(4, 2)

In [60]:
# reshape the array to 12 x 1
array12 = np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])
new2 = np.reshape(array12,(12,1))
new2

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [61]:
np.shape(new2)

(12, 1)

In [31]:
# transpose the array
array_t = array12.T

In [32]:
np.shape(array_t)

(12, 1)

In [37]:
# indexing method 1
y = np.array([1,2,3,4,5])
y[4]

5

In [45]:
# indexing method 1_2
z = np.array([[1,2,3,4,5,6],[7,7,7,7,7,7]])
z[1][2]

7

In [39]:
# indexing method 2
y[1:]

array([2, 3, 4, 5])

In [40]:
# indexing method 3- 2nd-5th entries 
y[1:4]

array([2, 3, 4])

In [64]:
# indexing method 4- create array for indexing

indexing = np.array([1,1])
x[indexing]

array([20, 20])

In [11]:
# indexing method 5-vals>3
x[x>3]
xy[0, xy[0]>3]

In [65]:
len(y)

5

In [66]:
sum(y)

15

In [109]:

few = np.array([1,2,3,4,5,6,7])
few

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
# indexing method 6- create a function that calculates the variance 
def var_calc(arrayname):
    mean_data = sum(arrayname) /len(arrayname)
    diff_squared = sum((arrayname - mean_data)**2)
    var_data = diff_squared / len(arrayname)
    return var_data
    


In [70]:
var_calc(y)

2

In [73]:
var_calc(d_array)

array([ 25, 100,   0,   0])

In [110]:
var_calc(few)

4

In [ ]:
# indexing method 6- create a function in a fn that calculates the stdev

In [80]:

def st_dev(arrayname):
    stdev = (var_calc(arrayname))**0.5
    return stdev
    

In [81]:
st_dev(y)

1.4142135623730951

In [111]:
st_dev(few)

2.0

In [112]:
import numpy as np
def statvals(arrayname):
    var_array = arrayname.var()
    return var_array


In [99]:
statvals(y)

2.0

In [113]:
statvals(few)

4.0

In [100]:
def std_dev(arrayname):
    stdev = (statvals(arrayname))**0.5
    return stdev

In [101]:
std_dev(y)

1.4142135623730951

In [102]:
std_dev(d_array)

6.8999547099962912

In [114]:
std_dev(few)

2.0